import type { Agent } from "@/lib/types";

function randomLatencyHistory(): number[] {
  return Array.from({ length: 20 }, (_, i) => {
    const base = 120 + Math.sin(i / 3) * 40;
    return Math.round(base + (Math.random() - 0.5) * 30);
  });
}

export const agents: Agent[] = [
  {
    id: "AGT-001",
    name: "Document Classifier",
    type: "Classification",
    model: "gpt-4o-mini-2024-07-18",
    status: "active",
    health: 98,
    cpuUsage: 42,
    memoryUsage: 61,
    processingLoad: 78,
    avgResponseLatency: 124,
    p99Latency: 310,
    assignedTasks: 847,
    completedToday: 12483,
    queueDepth: 124,
    uptime: "18d 7h 42m",
    lastActivity: new Date(Date.now() - 3 * 1000).toISOString(),
    confidenceAvg: 94.2,
    latencyHistory: randomLatencyHistory(),
  },
  {
    id: "AGT-002",
    name: "Support Triage Agent",
    type: "NLP Routing",
    model: "gpt-4o-2024-11-20",
    status: "active",
    health: 96,
    cpuUsage: 67,
    memoryUsage: 74,
    processingLoad: 91,
    avgResponseLatency: 89,
    p99Latency: 245,
    assignedTasks: 2341,
    completedToday: 38927,
    queueDepth: 412,
    uptime: "24d 12h 18m",
    lastActivity: new Date(Date.now() - 1 * 1000).toISOString(),
    confidenceAvg: 91.7,
    latencyHistory: randomLatencyHistory(),
  },
  {
    id: "AGT-003",
    name: "Invoice Processing Agent",
    type: "OCR + Extraction",
    model: "claude-3-5-sonnet-20241022",
    status: "active",
    health: 89,
    cpuUsage: 58,
    memoryUsage: 82,
    processingLoad: 65,
    avgResponseLatency: 312,
    p99Latency: 780,
    assignedTasks: 341,
    completedToday: 4821,
    queueDepth: 67,
    uptime: "11d 3h 5m",
    lastActivity: new Date(Date.now() - 8 * 1000).toISOString(),
    confidenceAvg: 96.1,
    latencyHistory: randomLatencyHistory(),
  },
  {
    id: "AGT-004",
    name: "Risk Analysis Agent",
    type: "Legal Intelligence",
    model: "claude-3-5-sonnet-20241022",
    status: "degraded",
    health: 62,
    cpuUsage: 88,
    memoryUsage: 91,
    processingLoad: 97,
    avgResponseLatency: 1840,
    p99Latency: 4200,
    assignedTasks: 87,
    completedToday: 412,
    queueDepth: 203,
    uptime: "7d 21h 33m",
    lastActivity: new Date(Date.now() - 42 * 1000).toISOString(),
    confidenceAvg: 88.5,
    latencyHistory: randomLatencyHistory().map((v) => v * 4),
  },
  {
    id: "AGT-005",
    name: "Knowledge Retrieval Agent",
    type: "RAG / Embeddings",
    model: "text-embedding-3-large",
    status: "active",
    health: 100,
    cpuUsage: 23,
    memoryUsage: 44,
    processingLoad: 31,
    avgResponseLatency: 67,
    p99Latency: 180,
    assignedTasks: 1284,
    completedToday: 28471,
    queueDepth: 18,
    uptime: "32d 4h 11m",
    lastActivity: new Date(Date.now() - 500).toISOString(),
    confidenceAvg: 99.1,
    latencyHistory: randomLatencyHistory().map((v) => Math.round(v * 0.4)),
  },
  {
    id: "AGT-006",
    name: "Medical NER Agent",
    type: "Clinical Extraction",
    model: "med-palm-2",
    status: "idle",
    health: 100,
    cpuUsage: 4,
    memoryUsage: 32,
    processingLoad: 8,
    avgResponseLatency: 890,
    p99Latency: 2100,
    assignedTasks: 0,
    completedToday: 1248,
    queueDepth: 0,
    uptime: "5d 16h 44m",
    lastActivity: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    confidenceAvg: 96.7,
    latencyHistory: randomLatencyHistory().map((v) => v * 6),
  },
];

export function getAgentById(id: string): Agent | undefined {
  return agents.find((a) => a.id === id);
}
