import type { LogEntry } from "@/lib/types";

function ts(minutesAgo: number): string {
  return new Date(Date.now() - minutesAgo * 60 * 1000).toISOString();
}

export const logs: LogEntry[] = [
  {
    id: "LOG-84921",
    timestamp: ts(0.1),
    severity: "info",
    source: "orchestrator",
    event: "WORKFLOW_TICK",
    message: "Workflow WF-2851 heartbeat received. Queue depth: 412. Throughput: 1840 docs/hr.",
    traceId: "trace-a8f2c1",
    workflowId: "WF-2851",
    metadata: { queue_depth: 412, throughput: 1840 },
  },
  {
    id: "LOG-84920",
    timestamp: ts(0.3),
    severity: "info",
    source: "AGT-002",
    event: "TASK_COMPLETED",
    message: "Task TASK-48297 completed. Classification: 'Billing Inquiry'. Confidence: 93.2%. Latency: 87ms.",
    traceId: "trace-b3d91e",
    taskId: "TASK-48297",
    workflowId: "WF-2851",
    metadata: { confidence: 93.2, latency_ms: 87, classification: "Billing Inquiry" },
  },
  {
    id: "LOG-84918",
    timestamp: ts(0.8),
    severity: "warn",
    source: "AGT-004",
    event: "HIGH_LATENCY_ALERT",
    message: "Risk Analysis Agent p99 latency exceeded 4000ms threshold. Current: 4200ms. Investigating memory pressure.",
    traceId: "trace-c7f84b",
    metadata: { p99_latency_ms: 4200, threshold_ms: 4000, memory_usage: 91 },
  },
  {
    id: "LOG-84915",
    timestamp: ts(1.2),
    severity: "error",
    source: "WF-2871",
    event: "STEP_FAILED",
    message: "Step 'Feature Engineering' failed in workflow WF-2871. Error: OutOfMemoryError during gradient computation. Retry 1/3 scheduled.",
    traceId: "trace-d2a71c",
    workflowId: "WF-2871",
    taskId: "TASK-48280",
    metadata: { step: "Feature Engineering", retry_attempt: 1, max_retries: 3, error_type: "OutOfMemoryError" },
  },
  {
    id: "LOG-84912",
    timestamp: ts(2.1),
    severity: "info",
    source: "AGT-001",
    event: "BATCH_PROCESSED",
    message: "Document batch DOC-BATCH-8421 processed. 48 documents classified. Avg confidence: 94.2%. Duration: 5840ms.",
    traceId: "trace-e9b32f",
    metadata: { batch_size: 48, avg_confidence: 94.2, duration_ms: 5840 },
  },
  {
    id: "LOG-84909",
    timestamp: ts(3.4),
    severity: "critical",
    source: "pipeline-monitor",
    event: "QUEUE_SATURATION",
    message: "CRITICAL: Human Review queue approaching saturation. Current depth: 3241. Capacity limit: 4000. Consider scaling review team.",
    traceId: "trace-f1c84d",
    metadata: { queue_depth: 3241, capacity_limit: 4000, saturation_pct: 81.0 },
  },
  {
    id: "LOG-84906",
    timestamp: ts(4.2),
    severity: "info",
    source: "AGT-005",
    event: "EMBEDDING_SYNC",
    message: "Knowledge base embedding sync completed. 1,248 new vectors upserted. Index size: 2.4M vectors. Latency: 67ms avg.",
    traceId: "trace-g4e21a",
    metadata: { vectors_upserted: 1248, total_vectors: 2400000, avg_latency_ms: 67 },
  },
  {
    id: "LOG-84903",
    timestamp: ts(5.8),
    severity: "warn",
    source: "AGT-004",
    event: "MEMORY_PRESSURE",
    message: "Risk Analysis Agent memory usage at 91%. GC cycles increasing. Performance degradation expected if usage exceeds 95%.",
    traceId: "trace-h8f31b",
    metadata: { memory_usage_pct: 91, gc_cycles_per_min: 12, threshold_pct: 95 },
  },
  {
    id: "LOG-84899",
    timestamp: ts(7.1),
    severity: "info",
    source: "WF-2847",
    event: "WORKFLOW_STARTED",
    message: "Workflow WF-2847 triggered by webhook. Source: api-gateway. Processing 47 incoming invoice documents.",
    traceId: "trace-i2c99e",
    workflowId: "WF-2847",
    metadata: { trigger: "webhook", document_count: 47, source: "api-gateway" },
  },
  {
    id: "LOG-84897",
    timestamp: ts(8.4),
    severity: "error",
    source: "WF-2871",
    event: "RETRY_FAILED",
    message: "Retry 2/3 failed for TASK-48280. Same error persists. OutOfMemoryError during gradient computation. Retry 3 in 30s.",
    traceId: "trace-d2a71c",
    workflowId: "WF-2871",
    taskId: "TASK-48280",
    metadata: { retry_attempt: 2, next_retry_ms: 30000, error_type: "OutOfMemoryError" },
  },
  {
    id: "LOG-84894",
    timestamp: ts(10.2),
    severity: "info",
    source: "system",
    event: "MODEL_ROTATED",
    message: "AGT-003 model rotated to claude-3-5-sonnet-20241022 for cost optimization. Previous: gpt-4o. Confidence delta: +1.2%.",
    traceId: "trace-j7d42c",
    metadata: { previous_model: "gpt-4o", new_model: "claude-3-5-sonnet-20241022", confidence_delta: 1.2 },
  },
  {
    id: "LOG-84891",
    timestamp: ts(12.8),
    severity: "debug",
    source: "AGT-003",
    event: "OCR_RESULT",
    message: "OCR extraction complete for DOC-5521. Pages: 4. Extracted fields: 23. Null fields: 1 (tax_exempt_status).",
    traceId: "trace-k3b81f",
    taskId: "TASK-48291",
    metadata: { pages: 4, extracted_fields: 23, null_fields: 1, missing_field: "tax_exempt_status" },
  },
  {
    id: "LOG-84887",
    timestamp: ts(15.3),
    severity: "info",
    source: "review-queue",
    event: "ITEM_ESCALATED",
    message: "Review item REV-10441 escalated to Legal team. Escalation reason: GDPR Art. 46 cross-border data transfer clause.",
    traceId: "trace-l9a14c",
    metadata: { review_id: "REV-10441", escalation_target: "Legal", reason: "GDPR Article 46" },
  },
  {
    id: "LOG-84883",
    timestamp: ts(18.7),
    severity: "warn",
    source: "scheduler",
    event: "SCHEDULE_DRIFT",
    message: "Workflow WF-2839 execution drifted by 4.2 minutes from scheduled time. System load: 87%. Adjusting next run.",
    traceId: "trace-m2f77b",
    workflowId: "WF-2839",
    metadata: { drift_minutes: 4.2, system_load_pct: 87, next_run_adjusted: 1 },
  },
  {
    id: "LOG-84880",
    timestamp: ts(21.4),
    severity: "info",
    source: "AGT-001",
    event: "CONFIDENCE_CALIBRATION",
    message: "Document Classifier confidence calibration updated. New threshold: 85.0%. Previous: 82.5%. 1,247 samples used.",
    traceId: "trace-n6c82d",
    metadata: { new_threshold: 85.0, previous_threshold: 82.5, calibration_samples: 1247 },
  },
  {
    id: "LOG-84876",
    timestamp: ts(24.9),
    severity: "critical",
    source: "WF-2871",
    event: "WORKFLOW_FAILED",
    message: "CRITICAL: Workflow WF-2871 (Fraud Detection Sweep) failed after 3 retries. Max retry limit reached. Manual intervention required.",
    traceId: "trace-d2a71c",
    workflowId: "WF-2871",
    metadata: { retries_exhausted: 3, failure_step: "Feature Engineering", manual_intervention_required: 1 },
  },
  {
    id: "LOG-84872",
    timestamp: ts(28.1),
    severity: "info",
    source: "system",
    event: "AGENT_SCALED",
    message: "AGT-002 (Support Triage) auto-scaled. Reason: queue_depth > 300. New instances: 2 → 3. Expected latency improvement: 28%.",
    traceId: "trace-o8d93a",
    metadata: { agent_id: "AGT-002", scale_trigger: "queue_depth > 300", prev_instances: 2, new_instances: 3 },
  },
  {
    id: "LOG-84869",
    timestamp: ts(32.6),
    severity: "info",
    source: "WF-2864",
    event: "SYNC_COMPLETED",
    message: "Knowledge Base Sync WF-2864 completed successfully. 8,421 documents synced. 1,248 new vectors. Duration: 47m 12s.",
    traceId: "trace-p3b14e",
    workflowId: "WF-2864",
    metadata: { docs_synced: 8421, new_vectors: 1248, duration_seconds: 2832 },
  },
  {
    id: "LOG-84865",
    timestamp: ts(37.4),
    severity: "debug",
    source: "AGT-005",
    event: "VECTOR_QUERY",
    message: "RAG query executed. Namespace: product-docs. Top-k: 5. Similarity threshold: 0.82. Results returned: 5. Latency: 67ms.",
    traceId: "trace-q7e21f",
    metadata: { namespace: "product-docs", top_k: 5, similarity_threshold: 0.82, results: 5, latency_ms: 67 },
  },
  {
    id: "LOG-84861",
    timestamp: ts(42.8),
    severity: "warn",
    source: "pipeline-monitor",
    event: "THROUGHPUT_DROP",
    message: "Validation stage throughput dropped 33% in last 5 minutes. Current: 187/min. Baseline: 280/min. Investigating.",
    traceId: "trace-r2c48b",
    metadata: { current_throughput: 187, baseline_throughput: 280, drop_pct: 33 },
  },
  {
    id: "LOG-84857",
    timestamp: ts(48.2),
    severity: "info",
    source: "review-queue",
    event: "ITEM_APPROVED",
    message: "Review item REV-10438 approved by compliance team. Reviewer: Dr. Compliance Officer. Audit trail recorded.",
    traceId: "trace-s9f71c",
    metadata: { review_id: "REV-10438", reviewer: "Dr. Compliance Officer", outcome: "approved" },
  },
  {
    id: "LOG-84853",
    timestamp: ts(54.7),
    severity: "error",
    source: "AGT-006",
    event: "PHI_REDACTION_BELOW_THRESHOLD",
    message: "PHI redaction confidence 72.1% on MRN-847291 — below 95% HIPAA compliance threshold. Item sent to human review.",
    traceId: "trace-t4b82d",
    taskId: "TASK-48264",
    metadata: { confidence: 72.1, threshold: 95.0, compliance_framework: "HIPAA", review_id: "REV-10469" },
  },
  {
    id: "LOG-84849",
    timestamp: ts(61.3),
    severity: "info",
    source: "system",
    event: "SYSTEM_HEALTH_CHECK",
    message: "Scheduled system health check completed. All services operational. 1 agent degraded (AGT-004). Alerts sent to ops@neuralops.ai.",
    traceId: "trace-u8e93a",
    metadata: { services_healthy: 11, services_degraded: 1, alerts_sent: 1 },
  },
];

export function getLogsBySeverity(severity: string): LogEntry[] {
  if (severity === "all") return logs;
  return logs.filter((l) => l.severity === severity);
}

export function searchLogs(query: string): LogEntry[] {
  const q = query.toLowerCase();
  return logs.filter(
    (l) =>
      l.message.toLowerCase().includes(q) ||
      l.event.toLowerCase().includes(q) ||
      l.source.toLowerCase().includes(q) ||
      (l.workflowId?.toLowerCase().includes(q) ?? false) ||
      (l.taskId?.toLowerCase().includes(q) ?? false)
  );
}
