import type { PipelineStage } from "@/lib/types";

export const pipelineStages: PipelineStage[] = [
  {
    id: "stage-ingestion",
    name: "Document Ingestion",
    shortName: "Ingestion",
    icon: "upload",
    status: "healthy",
    queueSize: 1247,
    throughput: 312,
    processingRate: 400,
    rejectionRate: 1.2,
    confidenceAvg: 99.8,
    errorCount: 3,
    avgLatencyMs: 180,
    lastUpdated: new Date(Date.now() - 2000).toISOString(),
  },
  {
    id: "stage-classification",
    name: "AI Classification",
    shortName: "Classification",
    icon: "brain",
    status: "healthy",
    queueSize: 847,
    throughput: 298,
    processingRate: 350,
    rejectionRate: 4.8,
    confidenceAvg: 92.4,
    errorCount: 14,
    avgLatencyMs: 1240,
    lastUpdated: new Date(Date.now() - 1800).toISOString(),
  },
  {
    id: "stage-validation",
    name: "Field Validation",
    shortName: "Validation",
    icon: "shield-check",
    status: "degraded",
    queueSize: 1842,
    throughput: 187,
    processingRate: 280,
    rejectionRate: 12.3,
    confidenceAvg: 84.1,
    errorCount: 47,
    avgLatencyMs: 2100,
    lastUpdated: new Date(Date.now() - 5000).toISOString(),
  },
  {
    id: "stage-review",
    name: "Human Review",
    shortName: "Review",
    icon: "user-check",
    status: "critical",
    queueSize: 3241,
    throughput: 42,
    processingRate: 60,
    rejectionRate: 28.4,
    confidenceAvg: 71.2,
    errorCount: 0,
    avgLatencyMs: 0, // human-driven
    lastUpdated: new Date(Date.now() - 30000).toISOString(),
  },
  {
    id: "stage-storage",
    name: "Secure Storage",
    shortName: "Storage",
    icon: "database",
    status: "healthy",
    queueSize: 124,
    throughput: 41,
    processingRate: 120,
    rejectionRate: 0.1,
    confidenceAvg: 100,
    errorCount: 0,
    avgLatencyMs: 115,
    lastUpdated: new Date(Date.now() - 1000).toISOString(),
  },
];
