import type { ReviewItem } from "@/lib/types";

export const reviewItems: ReviewItem[] = [
  {
    id: "REV-10481",
    taskId: "TASK-48291",
    documentId: "DOC-5521",
    documentType: "Invoice",
    title: "Vendor Invoice — Acme Corp Q4 2024",
    description: "AI confidence below threshold on tax exemption field. Manual verification required for tax ID validation.",
    aiConfidence: 61.4,
    confidenceThreshold: 85.0,
    status: "pending",
    priority: "high",
    flaggedReason: "Low confidence on tax exemption classification",
    flaggedFields: ["tax_exempt_status", "vendor_tax_id", "total_amount"],
    assignedAgent: "AGT-003",
    submittedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    auditTags: ["finance", "tax", "vendor"],
    previewData: {
      vendor_name: "Acme Corporation Ltd.",
      invoice_number: "INV-2024-09847",
      invoice_date: "2024-12-15",
      total_amount: "$48,291.00",
      tax_exempt_status: "EXEMPT (unverified)",
      vendor_tax_id: "83-1**4921",
      payment_terms: "NET-30",
    },
  },
  {
    id: "REV-10474",
    taskId: "TASK-48277",
    documentId: "DOC-5498",
    documentType: "Contract",
    title: "Service Agreement — DataFlow Inc.",
    description: "Unusual liability clause detected. Risk score exceeds threshold. Legal team review required.",
    aiConfidence: 54.8,
    confidenceThreshold: 80.0,
    status: "pending",
    priority: "critical",
    flaggedReason: "High-risk liability clause detected — potential compliance violation",
    flaggedFields: ["liability_cap", "indemnification_clause", "governing_law"],
    assignedAgent: "AGT-004",
    submittedAt: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    auditTags: ["legal", "contract", "risk"],
    previewData: {
      party_a: "NeuralOps Technologies Inc.",
      party_b: "DataFlow Inc.",
      contract_value: "$2,400,000.00",
      liability_cap: "UNLIMITED (flagged)",
      jurisdiction: "Delaware, USA",
      term_length: "36 months",
      auto_renewal: "Yes",
    },
  },
  {
    id: "REV-10469",
    taskId: "TASK-48264",
    documentId: "DOC-5471",
    documentType: "Medical Record",
    title: "Clinical Notes — Patient ID MRN-847291",
    description: "PHI redaction confidence insufficient. Critical fields may contain unredacted identifiers.",
    aiConfidence: 72.1,
    confidenceThreshold: 95.0,
    status: "pending",
    priority: "critical",
    flaggedReason: "PHI redaction confidence below HIPAA compliance threshold",
    flaggedFields: ["patient_name", "address_field", "dob_field", "ssn_partial"],
    assignedAgent: "AGT-006",
    submittedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    auditTags: ["hipaa", "healthcare", "phi"],
    previewData: {
      facility: "St. Mary Medical Center",
      admission_date: "2024-12-18",
      diagnosis: "Acute Appendicitis (ICD-10: K35.89)",
      attending_physician: "Dr. [REDACTED?]",
      patient_dob: "[POSSIBLY UNREDACTED]",
      insurance_id: "BCB-**7-481-920",
    },
  },
  {
    id: "REV-10458",
    taskId: "TASK-48241",
    documentId: "DOC-5442",
    documentType: "KYC Document",
    title: "Identity Verification — Alex Thornton",
    description: "Document authenticity score below threshold. Possible ID forgery pattern detected.",
    aiConfidence: 48.2,
    confidenceThreshold: 90.0,
    status: "pending",
    priority: "high",
    flaggedReason: "Forgery detection model flagged inconsistencies in document metadata",
    flaggedFields: ["id_authenticity_score", "document_expiry", "mrz_checksum"],
    assignedAgent: "AGT-001",
    submittedAt: new Date(Date.now() - 87 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    auditTags: ["kyc", "fraud", "identity"],
    previewData: {
      full_name: "Alex J. Thornton",
      document_type: "Passport",
      issuing_country: "United States",
      document_number: "A92847***",
      expiry_date: "2026-03-14",
      authenticity_score: "48/100 (FAIL)",
    },
  },
  {
    id: "REV-10451",
    taskId: "TASK-48218",
    documentId: "DOC-5411",
    documentType: "Support Ticket",
    title: "Escalation — Enterprise Customer Outage",
    description: "Support triage agent classified as medium priority but customer SLA indicates critical escalation required.",
    aiConfidence: 67.3,
    confidenceThreshold: 75.0,
    status: "pending",
    priority: "high",
    flaggedReason: "SLA breach risk — priority misclassification detected",
    flaggedFields: ["priority_classification", "sla_tier", "escalation_path"],
    assignedAgent: "AGT-002",
    submittedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    auditTags: ["cx", "sla", "escalation"],
    previewData: {
      customer: "Momentum Analytics (Enterprise)",
      sla_tier: "Platinum — 2hr response",
      original_classification: "Medium (P3)",
      recommended_classification: "Critical (P1)",
      impacted_users: "2,400",
      outage_duration: "47 minutes",
    },
  },
  {
    id: "REV-10447",
    taskId: "TASK-48199",
    documentId: "DOC-5384",
    documentType: "Invoice",
    title: "Duplicate Invoice Detection — Nexus Supplies",
    description: "Potential duplicate invoice flagged. Amount and vendor match existing record from 14 days ago.",
    aiConfidence: 83.4,
    confidenceThreshold: 85.0,
    status: "pending",
    priority: "medium",
    flaggedReason: "Near-duplicate match with existing approved invoice (INV-2024-09612)",
    flaggedFields: ["duplicate_score", "invoice_number", "submission_date"],
    assignedAgent: "AGT-003",
    submittedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    auditTags: ["finance", "duplicate", "vendor"],
    previewData: {
      vendor_name: "Nexus Office Supplies LLC",
      invoice_number: "NS-2024-1847",
      amount: "$12,480.00",
      original_invoice: "NS-2024-1721 ($12,480.00)",
      days_since_original: "14 days",
      duplicate_confidence: "83.4%",
    },
  },
  {
    id: "REV-10441",
    taskId: "TASK-48182",
    documentId: "DOC-5362",
    documentType: "Contract",
    title: "Vendor Agreement — Offshore Clause Review",
    description: "Contract contains data transfer clauses requiring GDPR compliance review before approval.",
    aiConfidence: 78.9,
    confidenceThreshold: 80.0,
    status: "escalated",
    priority: "critical",
    flaggedReason: "Cross-border data transfer clause — GDPR Article 46 review required",
    flaggedFields: ["data_transfer_clause", "gdpr_compliance", "subprocessor_list"],
    assignedAgent: "AGT-004",
    submittedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    reviewerNote: "Escalated to Legal. Awaiting DPO sign-off.",
    auditTags: ["gdpr", "legal", "compliance"],
    previewData: {
      vendor_name: "TechVision EU GmbH",
      transfer_destination: "India, Philippines",
      safeguards_listed: "None specified",
      gdpr_article: "Art. 46 — Transfers subject to appropriate safeguards",
      contract_effective: "2025-01-01",
    },
  },
  {
    id: "REV-10438",
    taskId: "TASK-48174",
    documentId: "DOC-5349",
    documentType: "Medical Record",
    title: "Billing Code Validation — Oncology Department",
    description: "Multiple ICD-10 codes flagged as potentially unbundled. Compliance team review recommended.",
    aiConfidence: 58.1,
    confidenceThreshold: 90.0,
    status: "approved",
    priority: "medium",
    flaggedReason: "ICD-10 code unbundling pattern detected",
    flaggedFields: ["icd10_codes", "cpt_codes", "bundling_compliance"],
    assignedAgent: "AGT-006",
    submittedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    dueBy: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    reviewerNote: "Reviewed by compliance team. Codes verified as appropriate. Approved.",
    auditTags: ["healthcare", "billing", "compliance"],
    previewData: {
      department: "Oncology",
      icd10_primary: "C34.10 — Lung malignancy",
      cpt_codes: "27447, 99213, 36415",
      flagged_pattern: "Potential code unbundling",
      reviewer: "Dr. Compliance Officer",
      review_date: "2024-12-18",
    },
  },
];

export function getReviewItemById(id: string): ReviewItem | undefined {
  return reviewItems.find((r) => r.id === id);
}

export function getReviewItemsByStatus(status: string): ReviewItem[] {
  if (status === "all") return reviewItems;
  return reviewItems.filter((r) => r.status === status);
}
