import type { Workflow } from "@/lib/types";

export const workflows: Workflow[] = [
  {
    id: "WF-2847",
    name: "Invoice Classification Pipeline",
    description:
      "Automatically classifies incoming invoice documents using GPT-4o, validates tax fields, and routes to appropriate review queues.",
    status: "running",
    trigger: "webhook",
    throughput: 342,
    avgProcessingTime: 1240,
    lastExecution: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    nextExecution: new Date(Date.now() + 18 * 60 * 1000).toISOString(),
    aiConfidence: 94.2,
    successRate: 97.8,
    totalRuns: 48291,
    failedRuns: 1063,
    tags: ["finance", "ocr", "classification"],
    dependencies: ["WF-2801", "WF-2815"],
    retryPolicy: { maxRetries: 3, backoffMs: 2000, strategy: "exponential" },
    steps: [
      { id: "s1", name: "PDF Ingestion", type: "ingestion", status: "completed", avgDurationMs: 180 },
      { id: "s2", name: "OCR Extraction", type: "classification", status: "completed", avgDurationMs: 420 },
      { id: "s3", name: "Field Validation", type: "validation", status: "running", avgDurationMs: 310 },
      { id: "s4", name: "Confidence Review", type: "review", status: "pending", avgDurationMs: 215 },
      { id: "s5", name: "Storage Commit", type: "storage", status: "pending", avgDurationMs: 115 },
    ],
  },
  {
    id: "WF-2851",
    name: "Support Ticket Triage",
    description:
      "Routes incoming support tickets by urgency and topic using a fine-tuned classification model. Integrates with CRM APIs for context enrichment.",
    status: "running",
    trigger: "event",
    throughput: 1840,
    avgProcessingTime: 380,
    lastExecution: new Date(Date.now() - 45 * 1000).toISOString(),
    nextExecution: undefined,
    aiConfidence: 91.7,
    successRate: 99.1,
    totalRuns: 182047,
    failedRuns: 1638,
    tags: ["nlp", "triage", "cx"],
    dependencies: [],
    retryPolicy: { maxRetries: 5, backoffMs: 500, strategy: "linear" },
    steps: [
      { id: "s1", name: "Ticket Ingestion", type: "ingestion", status: "running", avgDurationMs: 45 },
      { id: "s2", name: "Intent Classification", type: "classification", status: "pending", avgDurationMs: 185 },
      { id: "s3", name: "Priority Scoring", type: "validation", status: "pending", avgDurationMs: 95 },
      { id: "s4", name: "Queue Routing", type: "storage", status: "pending", avgDurationMs: 55 },
    ],
  },
  {
    id: "WF-2839",
    name: "Risk Document Analysis",
    description:
      "Analyzes contracts and legal documents for compliance risk indicators, generates structured risk summaries using claude-3-5-sonnet.",
    status: "running",
    trigger: "schedule",
    throughput: 87,
    avgProcessingTime: 4200,
    lastExecution: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    nextExecution: new Date(Date.now() + 46 * 60 * 1000).toISOString(),
    aiConfidence: 88.5,
    successRate: 95.2,
    totalRuns: 12847,
    failedRuns: 612,
    tags: ["legal", "risk", "nlp"],
    dependencies: ["WF-2812"],
    retryPolicy: { maxRetries: 2, backoffMs: 5000, strategy: "exponential" },
    steps: [
      { id: "s1", name: "Document Fetch", type: "ingestion", status: "completed", avgDurationMs: 320 },
      { id: "s2", name: "Clause Extraction", type: "classification", status: "running", avgDurationMs: 1840 },
      { id: "s3", name: "Risk Scoring", type: "validation", status: "pending", avgDurationMs: 1200 },
      { id: "s4", name: "Summary Generation", type: "review", status: "pending", avgDurationMs: 690 },
      { id: "s5", name: "Report Storage", type: "storage", status: "pending", avgDurationMs: 150 },
    ],
  },
  {
    id: "WF-2864",
    name: "Knowledge Base Sync",
    description:
      "Continuously syncs product documentation into vector embeddings for retrieval-augmented generation workflows.",
    status: "idle",
    trigger: "schedule",
    throughput: 0,
    avgProcessingTime: 2100,
    lastExecution: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    nextExecution: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    aiConfidence: 99.1,
    successRate: 99.8,
    totalRuns: 8421,
    failedRuns: 17,
    tags: ["embeddings", "rag", "sync"],
    dependencies: [],
    retryPolicy: { maxRetries: 3, backoffMs: 10000, strategy: "exponential" },
    steps: [
      { id: "s1", name: "Doc Crawl", type: "ingestion", status: "completed", avgDurationMs: 890 },
      { id: "s2", name: "Chunking", type: "classification", status: "completed", avgDurationMs: 340 },
      { id: "s3", name: "Embedding Generation", type: "validation", status: "completed", avgDurationMs: 710 },
      { id: "s4", name: "Vector Upsert", type: "storage", status: "completed", avgDurationMs: 160 },
    ],
  },
  {
    id: "WF-2871",
    name: "Fraud Detection Sweep",
    description:
      "Runs periodic fraud pattern detection against transaction logs using an ensemble of specialized models.",
    status: "error",
    trigger: "schedule",
    throughput: 0,
    avgProcessingTime: 8400,
    lastExecution: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    nextExecution: new Date(Date.now() + 32 * 60 * 1000).toISOString(),
    aiConfidence: 0,
    successRate: 87.3,
    totalRuns: 4821,
    failedRuns: 611,
    tags: ["fraud", "finance", "ml"],
    dependencies: ["WF-2847"],
    retryPolicy: { maxRetries: 3, backoffMs: 30000, strategy: "exponential" },
    steps: [
      { id: "s1", name: "Transaction Fetch", type: "ingestion", status: "completed", avgDurationMs: 1200 },
      { id: "s2", name: "Feature Engineering", type: "classification", status: "failed", avgDurationMs: 3100 },
      { id: "s3", name: "Ensemble Inference", type: "validation", status: "pending", avgDurationMs: 2800 },
      { id: "s4", name: "Alert Generation", type: "notification", status: "pending", avgDurationMs: 400 },
      { id: "s5", name: "Audit Log", type: "storage", status: "pending", avgDurationMs: 200 },
    ],
  },
  {
    id: "WF-2878",
    name: "Customer Onboarding Verification",
    description:
      "Verifies KYC documents, extracts PII fields, and performs compliance checks during customer onboarding flows.",
    status: "queued",
    trigger: "api",
    throughput: 0,
    avgProcessingTime: 3600,
    lastExecution: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    nextExecution: undefined,
    aiConfidence: 92.4,
    successRate: 96.1,
    totalRuns: 31847,
    failedRuns: 1241,
    tags: ["kyc", "compliance", "onboarding"],
    dependencies: [],
    retryPolicy: { maxRetries: 3, backoffMs: 2000, strategy: "linear" },
    steps: [
      { id: "s1", name: "Document Upload", type: "ingestion", status: "pending", avgDurationMs: 450 },
      { id: "s2", name: "ID Verification", type: "classification", status: "pending", avgDurationMs: 1200 },
      { id: "s3", name: "PII Extraction", type: "validation", status: "pending", avgDurationMs: 980 },
      { id: "s4", name: "Compliance Check", type: "review", status: "pending", avgDurationMs: 720 },
      { id: "s5", name: "Profile Creation", type: "storage", status: "pending", avgDurationMs: 250 },
    ],
  },
  {
    id: "WF-2881",
    name: "Email Sentiment Analysis",
    description:
      "Processes customer email batches through sentiment and topic modeling pipelines to generate ops insights.",
    status: "paused",
    trigger: "schedule",
    throughput: 0,
    avgProcessingTime: 620,
    lastExecution: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    nextExecution: new Date(Date.now() + 21 * 60 * 60 * 1000).toISOString(),
    aiConfidence: 89.3,
    successRate: 98.4,
    totalRuns: 62481,
    failedRuns: 999,
    tags: ["nlp", "sentiment", "cx"],
    dependencies: ["WF-2851"],
    retryPolicy: { maxRetries: 2, backoffMs: 1000, strategy: "linear" },
    steps: [
      { id: "s1", name: "Email Batch Fetch", type: "ingestion", status: "completed", avgDurationMs: 180 },
      { id: "s2", name: "Sentiment Scoring", type: "classification", status: "completed", avgDurationMs: 290 },
      { id: "s3", name: "Topic Clustering", type: "validation", status: "completed", avgDurationMs: 110 },
      { id: "s4", name: "Report Generation", type: "storage", status: "completed", avgDurationMs: 40 },
    ],
  },
  {
    id: "WF-2884",
    name: "Medical Record Abstraction",
    description:
      "HIPAA-compliant medical record abstraction pipeline, extracting structured data from unstructured clinical notes.",
    status: "running",
    trigger: "webhook",
    throughput: 54,
    avgProcessingTime: 6800,
    lastExecution: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    nextExecution: undefined,
    aiConfidence: 96.7,
    successRate: 98.9,
    totalRuns: 8421,
    failedRuns: 93,
    tags: ["healthcare", "nlp", "hipaa"],
    dependencies: [],
    retryPolicy: { maxRetries: 4, backoffMs: 3000, strategy: "exponential" },
    steps: [
      { id: "s1", name: "Record Ingestion", type: "ingestion", status: "completed", avgDurationMs: 420 },
      { id: "s2", name: "NER Extraction", type: "classification", status: "running", avgDurationMs: 2800 },
      { id: "s3", name: "ICD-10 Coding", type: "validation", status: "pending", avgDurationMs: 1900 },
      { id: "s4", name: "PHI Redaction", type: "review", status: "pending", avgDurationMs: 1200 },
      { id: "s5", name: "Secure Storage", type: "storage", status: "pending", avgDurationMs: 480 },
    ],
  },
];

export function getWorkflowById(id: string): Workflow | undefined {
  return workflows.find((w) => w.id === id);
}

export function getWorkflowsByStatus(status: string): Workflow[] {
  if (status === "all") return workflows;
  return workflows.filter((w) => w.status === status);
}

export const workflowStatusCounts = {
  running: workflows.filter((w) => w.status === "running").length,
  idle: workflows.filter((w) => w.status === "idle").length,
  error: workflows.filter((w) => w.status === "error").length,
  paused: workflows.filter((w) => w.status === "paused").length,
  queued: workflows.filter((w) => w.status === "queued").length,
  completed: workflows.filter((w) => w.status === "completed").length,
};
